sPHENIX-Collaboration/QAhtml

subsystems/example/macros/draw_example.C
Adds example macro which shows how to generate the html file from a dummy root file
=> feat: add example macro

client/OnlProdClient.cc
After talking to Chris, it was a mistake to change this. I did change the name of the variable though -- "ONLPROD_HTMLDIR" --> "QA_HTMLDIR"
=> Reverted back to using environment variable for top level directory

subsystems/calo/Makefile.am
This PR is a rename from OnlProd to QADraw, fixes a bunch of warnings - it's work in progress, just to get this out there that nobody tries to modify outdated code
=> add path to sphenixstyle

aggregate/aggregate_qa_histos.pl, makehtml/makehtml.py, makehtml/setup_all.sh, subsystems/calo/macros/makehtml.sh
This PR adds the script which creates the calo html archive using Xvfb, update aggregate scripts
=> add html cron scripts

subsystems/calo/CaloDraw.cc, subsystems/calo/CaloDraw.h
Moved both EMCal plots under one folder. Consolidated correlation plots into one page. Nicer menu names. Removed most of the unnecessary stats box contents. Larger axis titles and labels. Added tick marks on top and right axes.
=> Aesthetic changes for CaloDraw

configure.ac, subsystems/Makefile.am, subsystems/micromegas/Makefile.am, subsystems/micromegas/MicromegasDraw.cc, subsystems/micromegas/MicromegasDraw.h, subsystems/micromegas/macros/draw_micromegas.C, subsystems/tpc/TPCDraw.cc, subsystems/vertex/Makefile.am, subsystems/vertex/VertexDraw.cc, subsystems/vertex/VertexDraw.h, subsystems/vertex/macros/draw_vertex.C
Will be adding more for MVTX and INTT once I'm able to add more QA plots for those detectors. I'm also updating a couple of issues with the TPC module that I noticed here too
=> New QAHtml modules for Vertex and TPOT QA histograms

configure.ac, subsystems/Makefile.am, subsystems/bco/BCODraw.cc, subsystems/bco/BCODraw.h, subsystems/bco/Makefile.am
Draws BCO QA information for each of the tracking subsystems using the macros written by Joe and Hugo
=> New drawing module for event building QA plots

subsystems/calo/CaloDraw.cc, subsystems/calo/CaloDraw.h, subsystems/calo/CaloGoodRunChecker.cc, subsystems/calo/CaloGoodRunChecker.h, subsystems/calo/Makefile.am, subsystems/calo/macros/draw_calo.C
Added a new class `CaloGoodRunChecker` for good/bad run determination. It creates a "summary" canvas with key QA info for the EMCal. Also made tower masking maps available for the HCal.
=> Added EMCal good run checking and summary tab

client/QADrawClient.cc, client/QADrawClient.h, client/QARunDBodbc.cc, client/QARunDBodbc.h, subsystems/calo/CaloGoodRunChecker.cc, subsystems/calo/macros/draw_calo.C
This is to make the timestamp conveniently accessible to the drawing code
=> Added run timestamp string to QADrawClient

subsystems/trackseeds/Makefile.am, subsystems/trackseeds/TpcSeedsDraw.cc, subsystems/trackseeds/TpcSeedsDraw.h, subsystems/trackseeds/macros/draw_tpcseeds.C
Integrating TpcSeedsQA to QAhtml for display. An example for run 41992 can be found in https://sphenix-intra.sdcc.bnl.gov/WWW/subsystem/QAHtmlTest/mon.cgi?runnumber=41992&runtype=beam
=> TPC Seeds QA

subsystems/intt/INTTDraw.cc, subsystems/intt/INTTDraw.h, subsystems/mvtx/MVTXDraw.cc, subsystems/mvtx/MVTXDraw.h, subsystems/trackseeds/SiliconSeedsDraw.cc, subsystems/trackseeds/SiliconSeedsDraw.h
Update silicon seeds, MVTX and INTT cluster QAs
=> Silicon seed & cluster QAs updated

subsystems/mvtx/MVTXRawHitDraw.cc, subsystems/mvtx/MVTXRawHitDraw.h, subsystems/mvtx/Makefile.am, subsystems/mvtx/macros/draw_mvtx_rawhit.C, subsystems/trackseeds/TpcSeedsDraw.cc
Update Tpc Seeds QA html and add Mvtx Raw Hit QA html.
=> Trackingqa

subsystems/calo/CaloGoodRunChecker.cc, subsystems/calo/CaloGoodRunChecker.h, subsystems/calo/Makefile.am, subsystems/calo/macros/draw_calo.C
Please merge before re-running calo QA
=> Added indicators for which EMCal criteria pass and which fail

subsystems/trackclusters/macros/draw_clusters.C
add macro to draw all cluster modules
=> feat: draw clus macro

subsystems/siliconseeds/OfflineQAKSTest.h, subsystems/siliconseeds/macros/draw_siliconseeds.C
=> Bug fix: draw_siliconseeds.C

subsystems/calo/CaloDraw.cc
remove logy in zdc draw and change location of line
=> remove logy in zdc draw

subsystems/mvtxrawhit/MVTXRawHitDraw.cc, subsystems/mvtxrawhit/MVTXRawHitDraw.h, subsystems/tpcseeds/TpcSeedsDraw.cc, subsystems/tpcseeds/TpcSeedsDraw.h, subsystems/tpcseeds/macros/draw_tpcseeds.C
Update TpcSeedsQA and MvtxRawHitQA QAhtml
=> Tpc seeds mvtx raw hit qa

subsystems/mvtx/MVTXDraw.cc, subsystems/mvtx/MVTXDraw.h, subsystems/siliconseeds/OfflineQAKSTest.cc
- Add MVTX run status summary (determined based on cluster phi and chip occupancy)
- Draw histogram overflow bins (chip occupancy)
=> Add MVTX Cluster QA run summary

subsystems/mvtx/MVTXDraw.cc, subsystems/mvtx/MVTXDraw.h
- Update the MVTX run summary status
=> MVTX QA update

Makefile.am, database/Makefile.am, subsystems/calo/CaloDraw.cc, subsystems/calo/CaloDraw.h, subsystems/calo/CaloGoodRunChecker.cc, subsystems/calo/CaloGoodRunChecker.h, subsystems/calo/macros/draw_calo.C
Added the hot tower masking as well as the summary canvas that tells us if it was a good/bad run.
=> Adding the inner and outer hcal QA plots

subsystems/globalQA/GlobalQADraw.cc, subsystems/globalQA/GlobalQADraw.h
Added some plots and used the correct values for ZDC plots
=> plotted 2d plots

configure.ac, subsystems/Makefile.am, subsystems/bco/BCODraw.cc, subsystems/tpcrawhit/Makefile.am, subsystems/tpcrawhit/TPCRawHitDraw.cc, subsystems/tpcrawhit/TPCRawHitDraw.h, subsystems/tpcrawhit/macros/draw_tpc_rawhit.C, subsystems/tpcsil/Makefile.am, subsystems/tpcsil/TPCSilDraw.cc, subsystems/tpcsil/TPCSilDraw.h, subsystems/tpcsil/macros/draw_tpcsil.C
Adding drawing modules for TPCRawHitQA and TpcSiliconQA histograms 
Updating BCODraw module to reflect recent changes Joe made
=> New Drawing Modules and Updates to BCO Module

subsystems/calo/CaloGoodRunChecker.cc, subsystems/calo/CaloGoodRunChecker.cc.orig, subsystems/calo/CaloGoodRunChecker.h.orig, subsystems/calo/macros/draw_calo.C
I had accidentally reverted to an old version while fixing the last merge conflict. Re-updated now. Also added functionality to update the run triage database with HCal info -- works but not yet enabled in calo_draw.C
=> Fixed mistake in EMCal summary tab

subsystems/tpcsil/TPCSilDraw.cc, subsystems/tpcsil/TPCSilDraw.h
Adds drawing function for histograms with progressive cuts on xy, phi, and eta for the Tpc-Silicon difference plots
=> Adding Geometric Cut Histograms to TPCSilicon Drawing Module

subsystems/tpcrawhit/Makefile.am, subsystems/tpcrawhit/TPCRawHitDraw.cc
Adds fraction of straight tracks that would pass through 1, 2, and 3 FEEs in the TPCRawHitQA xy plot
Very clunky calculation for now, but should work and not take too long to run
Also displays the fraction of FEEs out for a given run
=> New Track FEE Fraction Information

makehtml/CaloDBAgg.py, makehtml/TrackerDBAgg.py
This adds python aggregation scripts that are based on look ups from the file db instead of assumptions of where the files exist.
=> feat: aggregation scripts based on file db

subsystems/intt/INTTChipDrawer.cc, subsystems/intt/INTTChipDrawer.h, subsystems/intt/INTTClusterDrawer.cc, subsystems/intt/INTTClusterDrawer.h, subsystems/intt/INTTDraw.cc, subsystems/intt/INTTDraw.h, subsystems/intt/Makefile.am, subsystems/intt/SingleCanvasDrawer.cc, subsystems/intt/SingleCanvasDrawer.h
Added base class for drawing options, implemented current options as derived classes, and rewrote client to handle a map of options as pointer-to-base class.
These changes should not reduce or expand functionality (for now). But I expect it to make it much, much easier for multiple people to work in parallel to expand options in the near future.
=> (INTT) Restructure for convenience, will add more using this pattern

subsystems/tpc/TPCDraw.cc, subsystems/tpc/TPCDraw.h, subsystems/tpcrawhit/TPCRawHitDraw.cc
Plot formatting to make some of the TPC offline QA figures look better and more understandable
Please wait to merge until I get the thumbs up that these all look ok from Anne and co!
=> Improvements to TPC QA Figure formatting

subsystems/tpcseeds/TpcSeedsDraw.cc, subsystems/tpcseeds/TpcSeedsDraw.h
Corresponding changes in drawing for [coresoftware PR](https://github.com/sPHENIX-Collaboration/coresoftware/pull/3113)
Example plots can be found in [QAhtmltest](https://sphenix-intra.sdcc.bnl.gov/WWW/subsystem/QAHtmlTest/mon.cgi?runnumber=51619&runtype=physics)
=> TpcSeedsQA draw update

subsystems/tpcsil/macros/draw_tpcsil.C
=> fix: add style

subsystems/tpcrawhit/macros/draw_tpc_rawhit.C
Fixing styles as we discuss the plots...
=> fix: another style

subsystems/globalQA/GlobalQADraw.cc, subsystems/globalQA/GlobalQADraw.h
Remove request for trigger histograms not made by globalQA and update to correct hist name for ZDC vertex
=> fix globalQA html drawing

subsystems/tpc/TPCDraw.cc, subsystems/tpcrawhit/TPCRawHitDraw.cc, subsystems/tpcsil/TPCSilDraw.cc
Axes labels updated to be compatible with sPHENIXStyle macro settings and colored graphs fixed in the figures that need it
=> Improvements to TPC Offline QA Figure Formatting

configure.ac, subsystems/Makefile.am, subsystems/jets/JetDraw.cc, subsystems/jets/JetDraw.h, subsystems/jets/Makefile.am, subsystems/jets/macros/draw_jet.C, subsystems/jets/macros/makehtml.sh
Awaiting comments from Derek Anderson for this draft PR
=> Commiting jet html directory, tested compilation

makehtml/CaloDBAgg.py, makehtml/TrackerDBAgg.py
This PR adds the jet histos to the aggregation script and updates the db queries to be more economical
=> feat: add jet to agg and improve query speed

subsystems/jets/JetDraw.cc, subsystems/jets/JetDraw.h
This PR fixes a couple typos in the names of some JetQA histograms
=> Fix typos in jet histogram names

makehtml/CaloDBAgg.py, makehtml/TrackerDBAgg.py
Expands scripts to iterate over run types
=> fix: expand run types

client/QADrawClient.cc, client/QADrawClient.h, subsystems/bco/BCODraw.cc, subsystems/calo/CaloDraw.cc, subsystems/globalQA/GlobalQADraw.cc, subsystems/intt/INTTChipDrawer.cc, subsystems/intt/INTTClusterDrawer.cc, subsystems/inttrawhit/INTTRawHitChipDrawer.cc, subsystems/inttrawhit/INTTRawHitSummaryDrawer.cc, subsystems/jets/JetDraw.cc, subsystems/micromegas/MicromegasDraw.cc, subsystems/mvtx/MVTXDraw.cc, subsystems/mvtxrawhit/MVTXRawHitDraw.cc, subsystems/siliconseeds/SiliconSeedsDraw.cc, subsystems/tpc/TPCDraw.cc, subsystems/tpcrawhit/TPCRawHitDraw.cc, subsystems/tpcseeds/TpcSeedsDraw.cc, subsystems/tpcsil/TPCSilDraw.cc, subsystems/vertex/VertexDraw.cc
This adds the build tag as an option to be extracted from the root file name, and then adds the plotting of the build tag in addition to the run number to the histos
=> feat: build tag

subsystems/micromegas/MicromegasDraw.cc, subsystems/micromegas/MicromegasDraw.h
Drawing the relevant QA histograms matching selection criteria for TPOT runQA
=> Implemented drawing methods for TPOT QA

subsystems/calo/CaloGoodRunChecker.cc, subsystems/tpcseeds/TpcSeedsDraw.cc
Updates QAhtml to compile with alma9
=> fix: a9 compilation

makehtml/CaloDBAgg.py, makehtml/TrackerDBAgg.py
Updates agg scripts to confirm to new production structure
=> fix: update aggscripts

makehtml/CaloDBAgg.py, makehtml/TrackerDBAgg.py
Adds the aggregated files and information about them to the file catalog
=> feat: add agg files to file catalog

makehtml/CaloDBAgg.py, makehtml/TrackerDBAgg.py, makehtml/makehtmlcalo.py, makehtml/makehtmltrackers.py
Improves the aggregation scripts and adds the calo html script
=> feat: improve python scripts

makehtml/BcoDBAgg.py, makehtml/BcoDBROCAgg.py
This updates the bco aggregation and roc bco aggregation scripts to be functional. Next up is to get the drawing script in place.
=> fix: update bco aggregation scripts

makehtml/makehtmlcalo.py, makehtml/makehtmltrackers.py, makehtml/makehtmltrackers.sh
This PR
1. "Parallelizes" the tracking html drawing, so that it doesn't take as long to draw due to the large numbers of files to process
2. Fixes the calo aggregation and html drawing to be functional
=> fix: improvements to html drawing

makehtml/BcoDBROCAgg.py, makehtml/makehtmltrackers.py, makehtml/makehtmltrackers.sh
BCO QA adds up intt/mvtx/tpc with 0 segment files from job-1
=> fix: bcoqa with 0 segments

subsystems/globalQA/GlobalQADraw.cc, subsystems/globalQA/GlobalQADraw.h, subsystems/globalQA/Makefile.am, subsystems/globalQA/macros/draw_GlobalQA.C
Uses RooFit to fit sEPD channel ADC spectra and saves the results.
=> Added MIP peak fit plots for sEPD

client/QADrawClient.cc, subsystems/bco/BCODraw.cc, subsystems/bco/macros/draw_packets.C
This adds an option to the tracking bco packet drawing to run each subsystem individually (since their histograms are now in different files)
=> feat: add packet drawing who option

configure.ac, subsystems/Makefile.am, subsystems/tpclasers/Makefile.am, subsystems/tpclasers/TPCLasersDraw.cc, subsystems/tpclasers/TPCLasersDraw.h, subsystems/tpclasers/macros/draw_tpclasers.C
=> Addition of TPCLaserQA drawing

client/QADrawClient.cc, makehtml/BcoDBAgg.py, makehtml/BcoDBROCAgg.py, makehtml/CaloDBAgg.py, makehtml/TrackerDBAgg.py, makehtml/makehtmltrackers.py, makehtml/makehtmltrackers.sh, makehtml/runaggtrackers.sh
This adds a variety of offline qa infrastructure developments to make the drawing and aggregation scripts more reliable
=> feat: offline qa development

subsystems/bco/BCODraw.cc, subsystems/bco/BCODraw.h
This PR updates the silicon BCO drawing to be compatible with the new server by server qa histogram workflow
=> fix: server by server silicon bco drawing

subsystems/siliconseeds/SiliconSeedsDraw.cc
Suppress this seg fault for right now
=> fix: suppress segfault

subsystems/tpclasers/TPCLasersDraw.cc, subsystems/tpclasers/TPCLasersDraw.h
Additional diffuse laser QA.
Needs https://github.com/sPHENIX-Collaboration/coresoftware/pull/3576
=> Diffuse laser QA

subsystems/micromegas/MicromegasDraw.cc, subsystems/micromegas/MicromegasDraw.h
=> Added raw QA histograms as a tab to TPOT

makehtml/BcoDBROCAgg.py, makehtml/makehtmltrackers.py, makehtml/makehtmltrackers.sh
This fixes up the scripts to run with the latest online production, using the bco qa as the test bed
=> fix: bco qa auto drawing

makehtml/BcoDBROCAgg.py, makehtml/CaloDBAgg.py, makehtml/makehtmlcalo.py, makehtml/makehtmlcalo.sh
This PR updates the aggregation scripts to deal with thew new calo production file catalog structure
=> fix: new file catalog structure

configure.ac, subsystems/Makefile.am, subsystems/calofitting/CaloFittingDraw.cc, subsystems/calofitting/CaloFittingDraw.h, subsystems/calofitting/Makefile.am, subsystems/calofitting/macros/draw_calo_fitting.C, subsystems/calofitting/macros/makehtml.sh
Creating new calofitting QAhtml module which shows details about ZS and run level packet alignment QA presented in collaboration meeting.
=> CaloFittingQA

client/SingleCanvasDrawer.cc, client/SingleCanvasDrawer.h, configure.ac, subsystems/Makefile.am, subsystems/intt/INTTChipDrawer.cc, subsystems/intt/INTTChipDrawer.h, subsystems/intt/INTTClusterDrawer.cc, subsystems/intt/INTTClusterDrawer.h, subsystems/inttrawhit/INTTRawHitChipDrawer.cc, subsystems/inttrawhit/INTTRawHitChipDrawer.h, subsystems/inttrawhit/INTTRawHitSummaryDrawer.cc, subsystems/inttrawhit/INTTRawHitSummaryDrawer.h, subsystems/tracking/Makefile.am, subsystems/tracking/Tracking1dPmDrawer.cc, subsystems/tracking/Tracking1dPmDrawer.h, subsystems/tracking/Tracking2dPmDrawer.cc, subsystems/tracking/Tracking2dPmDrawer.h, subsystems/tracking/TrackingDraw.cc, subsystems/tracking/TrackingDraw.h, subsystems/tracking/macros/draw_tracking.C
* Changed SingleCanvasDrawer so canvas size can be passed to the MakeCanvas method
* Implemented child classes for drawing tracking QA histograms
=> TrackFittingQA drawing module

subsystems/micromegas/MicromegasDraw.cc, subsystems/micromegas/MicromegasDraw.h
- corrected min values for cluster size and cluster multiplicity by -…0.5 due to incorrect binning
- changed histogram plotting order for raw histograms
- adjusted acceptable ranges.
=> more micromegas offline qa improvements

subsystems/bco/BCODraw.cc, subsystems/micromegas/MicromegasDraw.cc, subsystems/micromegas/MicromegasDraw.h
- renamed some methods for consistency with online monitoring code
- added per detector acceptable range
- (re) added BCO QA page (duplicated from the BCO subsystem
- some improvement on how the code behaves when histograms are not found.
=> Micromegas offline qa improvements 3

subsystems/calo/CaloDraw.h, subsystems/calo/CaloGoodRunChecker.h, subsystems/calo/macros/draw_calo.C
Updated the reference file to: "/sphenix/data/data02/sphnxpro/QAhtml/aggregated/run3auau/physics/ana492_2025p003_v005/caloy2calib/run_00067500_00067600/HIST_CALOQA_run3auau_ana492_2025p003_v005-00067526-9999.root" 
Added it to the following places: "CaloDraw.h", "CaloGoodRunChecker.h", and "macros/draw_calo.C".
=> Updated the reference run file 

subsystems/globalQA/GlobalQADraw.cc
Updated sEPD histogram drawing for AuAu data
=> updated sEPD histogram axis ranges and added log z axes for NS correlation plot

subsystems/micromegas/MicromegasDraw.h
Sorry! Realized I made a mistake in my previous PR
=> Corrected the threshold for NCIP, not NEIP from PR #150.

subsystems/tpcseeds/TpcSeedsDraw.cc, subsystems/tpcseeds/TpcSeedsDraw.h
1. Add sumarry page for TpcSeedsQA
criteria is dE/dx highZ/lowZ ratio < 1.4 and dEdx MPV >300
2. adjust TCanvas size and text size
=> add summary page for TpcSeedsQA Draw
