client/QAHtml.cc, client/QAHtml.h
root mkdir never set the permissions to group writable as intended. This PR fixes this using std::filesystem and stat to set the sticky bit
=> fix group writable directories

subsystems/Makefile.am, subsystems/tpc/TPCDraw.cc
Inadvertently removed tpc from makefile, and skip resid drawing for now so that other tpc cluster histos draw
=> don't do resid draw for now

subsystems/siliconseeds/OfflineQAKSTest.cc, subsystems/siliconseeds/OfflineQAKSTest.h, subsystems/siliconseeds/macros/draw_siliconseeds.C
- Updated `OfflineQAKSTest` module to allow for user specified option when running KS test.
- Changed default option from "D" to  "". 
- Added check for -1 (failed test) to output histogram. 
- Changed TProfile2D KSTest to not have to project to TH2D before doing the test.
=> Updated OfflineQAKSTest module to allow for user to specify option

subsystems/mvtx/MVTXDraw.h
- Update the thresholds for prompt run quality check: an updated version of the alignment file was used after Run 49961, resulting in a different shape of cluster phi distribution
=> MVTX QA update

subsystems/tpcseeds/TpcSeedsDraw.cc
In this PR, one pad fraction calculation is done in QAhtml. Reading numerator (sum of one pad fraction of each track) and denominator (sum of tracks), and then do ratio to get the average one pad fraction, rather than directly reading ratio from root file. The reason is that the aggregation add different root files together, ratio is not additive, but numerator and denominator are additive.
=> change calculation of one pad fraction in TPC seeds QA

subsystems/tpcrawhit/TPCRawHitDraw.cc, subsystems/tpcrawhit/TPCRawHitDraw.h, subsystems/tpcsil/TPCSilDraw.cc, subsystems/tpcsil/TPCSilDraw.h
Adding new drawing capabilities to reflect the changes made in coresoftware PR 3117
- North/South separated TpcSiliconQA plots for no cuts and all cuts
- Laser/no laser separation of TpcRawHitsQA histograms and improvements to how hits are determined and included needed some rescaling of plot axes
=> Improvements to TPC Offline QA Drawing Modules

client/SingleCanvasDrawer.cc
Using TROOT::FindObject instead of TSystem::FindObject since TSystem::FindObject always fails to find TCanvases
=> SingleCanvasDrawer Fix

subsystems/jets/JetDraw.cc, subsystems/jets/JetDraw.h, subsystems/jets/macros/draw_jet.C
This PR resolves a major bug introduced when switching over to vectors to manage canvases rather than c arrays: the old way of adding `TCanvas`s and `TPad`s to the vectors that tracked them resulted in several dangling pointers. Alongside this, this PR makes a few small fixes listed below.
Full list of changes:
- Uses `emplace_back()` rather than `push_back()` where needed;
- Removes now redundant vectors tracking pointers to individual pads;
- Adds an option to adjust verbosity;
- Draw options now throw error if they try to process an unknown resolution parameter;
- And redundant calls to `TStyle::SetColorPalette` were removed.
=> Squash major bug in JetQA

subsystems/jets/JetDraw.cc, subsystems/jets/JetDraw.h, subsystems/jets/macros/draw_jet.C
This PR adds a method to save all produced plots to a specified ROOT file and updates the `draw_jet.C` macro accordingly. This functionality was found to be useful in the initial debugging of `JetDraw`, and is very useful for quick turnaround when testing changes to the plotting details.
=> Add jet debugging tools

subsystems/micromegas/MicromegasDraw.cc, subsystems/micromegas/MicromegasDraw.h
This allows to not depend on the underlying  TH1/TH2 type when plotting Micromegas QA histogram.
+ some minor cleanup.
=> Fix micromegas histogram

client/QADrawClient.cc
Avoids some memory problems. Occasionally, CanvasToPng() will segfault on calling TCanvas::Print().
=> Changed CanvasToPng() to just call TCanvas::SaveAs()

subsystems/jets/JetDraw.cc
This PR updates the names of the various jet QA pages to indicate what's actually contained in them.
=> Make jet HTML page names descriptive

subsystems/globalQA/GlobalQADraw.cc, subsystems/globalQA/GlobalQADraw.h, subsystems/globalQA/Makefile.am, subsystems/globalQA/macros/draw_GlobalQA.C
This primarily changes the loop over sEPD tiles to loop over the geometry instead of "channels", which simplifies getting the geometry information. The geometry information was used to create a failure map for the fits to the ADC spectra from the tiles.
=> Changed sEPD fit loop + added fit failure map

subsystems/jets/JetDraw.cc, subsystems/jets/JetDraw.h, subsystems/jets/JetDrawDefs.h, subsystems/jets/Makefile.am
This pull request merges work by @jamesjl3,  @mitrankova, and @ruse-traveler which fixes several typos in labels, sets log of axes correctly, and ensures that no more than 4 histograms are plotted per page. It also adds docstrings to several places.
=> Fix labels/titles, split pages into no more than 4 histograms

subsystems/bco/BCODraw.cc, subsystems/micromegas/MicromegasDraw.cc
Moved TPOT BCO quality check plots to the BCO tab to be able to retrieve the histograms from the proper production .root files
=> TPOT QA plot corrections

subsystems/mvtxrawhit/MVTXRawHitDraw.cc
As part of Maria's request to update our offline QA, I've changed the divisions for the MVTX raw QA so the x-axis is legible
@osbornjd this is part of my general updates to the MVTX QA
=> CD: Changed x-axis divisions so its legible

subsystems/micromegas/MicromegasDraw.cc, subsystems/micromegas/MicromegasDraw.h
Another round of improvements to TPOT offline QA to make it 'offline-shifter' ready
- added BCO page with acceptable ranges, 
- added BCO summary page
- added colors
Summary pages now look like this:
@osbornjd the MicromegasDraw module should also be added to the list of QA post-processing modules that run at the raw-data event decoding stage (the creation of raw hits). It should gracefully handle BCO histograms, and skip the missing Cluster QA histograms. Could you do that ? And tell me if there is anything I can do to help ?
=> Micromegas offline qa improvements 4

configure.ac, subsystems/Makefile.am, subsystems/filetransfer/CheckFileTransfer.C, subsystems/filetransfer/CheckMissingFiles.C, subsystems/filetransfer/FileTransfer.cc, subsystems/filetransfer/FileTransfer.h, subsystems/filetransfer/FileTransferUtils.h, subsystems/filetransfer/Makefile.am, subsystems/filetransfer/macros/draw_filetransfer.C
This takes @hupereir original file transfer macros (also added to this package) and adapts them to use QAhtml for the drawing. Some examples of tests can be found in the QAHtmlTest page. Next is to add it to the drawing scripts, which may take some massaging (or an entirely new script) since there are no histogram files needed for this special QA
=> feat: file transfer QA

subsystems/jets/BaseJetDrawer.cc
Fixed an issue that QA plots production info was too small and located at incorrect position.
Updated the production info format to match current style.
=> Draw build and prod tag

subsystems/mvtx/MVTXDraw.cc, subsystems/mvtx/MVTXDraw.h
At Maria’s request, the line color has been changed to orange when the cosine modulation amplitude–to–average ratio indicator is marked as questionable
=> Change color for questionable B/A
